---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout # check out source code to working directory
      - run:
          name: npm build
          command: |
            npm install
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout # check out source code to working directory
      - run:
          name: npm build
          command: |
            echo "Hello World!"
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build:
    jobs:
    - build