---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:12.14.1
    steps:
			- checkout
			- run:
					name: npm build
					command: |
						npm install
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
			- checkout
			- run:
					name: npm build
					command: |
						npm install
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build:
    jobs:
    - build