---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout # check out source code to working directory
			- run:
					name: npm build
					command: |
						npm install
					name: npm test
					command: |
						npm test

  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout # check out source code to working directory
			- run: npm install
			- run: npm test
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build:
    jobs:
    - build
