---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout # check out source code to working directory
      - run: npm install
			- run: npm test
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout # check out source code to working directory
      - run: npm install
			- run: npm test
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build:
    jobs:
    - build